### ISSUE TITLE
Program nie chce się załadować(w Operze oraz w chromie)

### ISSUE THREAD

**Issue by AXTART** [docentYT/Librus-srednia#2]
Witam mam problem ponieważ Opera oraz Chrome nie chce załadować wtyczki. Wyświetla komunikat że brakuje mu pliku manifestu 
![Zrzut ekranu 2022-12-05 160245](https://user-images.githubusercontent.com/80387224/205669727-26ca8ff8-b452-4ea9-97e8-eb0f7ccd4505.png)
![image](https://user-images.githubusercontent.com/80387224/205669826-83142260-4743-416e-817f-f79d84c9a372.png)

**Comment by docentYT** [comment]
Cześć!
Do przeglądarki musisz załadować rozpakowany folder, ~~który jest podany w nagłówku przy przeglądarce w README.md~~ _(Wyłapałem błąd)_ (`extensions/combined/dist/chrome`). W tym folderze znajduje się plik manifest.json oraz kod wtyczki.

Daj znać czy działa.

**Comment by AXTART** [comment]
Dobra teraz działa. Ale i tak moi nauczyciele dają nie liczyć do średniej więc nic nie pokazuje.
